name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        working-directory: ./golem-ts-sdk
        run: |
          npm install

      - name: Build the package
        working-directory: ./golem-ts-sdk
        run: |
          npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          npm install

      - name: Build the package
        working-directory: ./golem-ts-sdk
        run: |
          npm run build

      - name: Publish to npm
        working-directory: ./golem-ts-sdk
        run: |
          npm publish --access public --tag test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}